### ISSUE TITLE
Cannot visualize the drugs in a network

### ISSUE THREAD

**Issue by guillermoturiel** [oubounyt/SCANet#3]
Hello, 

I have been testing your method and everything seems to work except for one thing. I can run the full script and get the GRN where I can visualize the TFs and their target genes. However when trying to run the last step of the script to see the drugs within the network I get the following error: 

> In [109]: sn.pl.plot_grn(df=grn_df, occurrence_pct=80, regulon="all", layout="None", drug_interaction="direct")
> 
>  Out of 389 edges, 67 edges satisfying occurrence threshold 80% where kept
> 
> ['NR2F2', 'CREB5', 'TBX1', 'NR2F1']
> (67, 3)
> None
> Local cdn resources have problems on chrome/safari when used in jupyter-notebook.
> INFO:root:degree progress is at: 0.0%
> INFO:root:degree is done.
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[109], line 1
> ----> 1 sn.pl.plot_grn(df=grn_df, occurrence_pct=80, regulon="all", layout="None", drug_interaction="direct")
> 
> File ~/anaconda3/envs/scanet/lib/python3.9/site-packages/scanet/plottingNetworks.py:98, in Plot.plot_grn(df, occurrence_pct, regulon, name, drug_interaction, algorithm, layout)
>      96 # drug interaction
>      97 if drug_interaction:
> ---> 98     drug_interactions = DrugInteractions.get_drug_interactions(net_genes, algorithm)
>      99     for inter in drug_interactions:
>     100         network.add_node(inter[0], shape='star', color='darkgreen')
> 
> File ~/anaconda3/envs/scanet/lib/python3.9/site-packages/scanet/drug_interactions.py:24, in DrugInteractions.get_drug_interactions(cls, genes, algorithm)
>      22 r = task.get_result()
>      23 if r.get_genes() == {}:
> ---> 24     also_broken = cls.find_broken(genes, algorithm=algorithm)
>      25     genes = [gene for gene in genes if gene not in also_broken]
>      26     task = new_task(genes, parameters)
> 
> AttributeError: type object 'DrugInteractions' has no attribute 'find_broken'

And then the html file with the GRN+drugs is not generated. I am bit lost on what is causing this problem so any help would be highly appreciated!

Thank you very much

Best
Guillermo

**Comment by oubounyt** [comment]
Hey,

Could you please remove the drug_interaction="direct" argument from the sn.pl.plot_grn function? 

I will investigate the error to determine which attribute in the package we use has changed for gene-drug interactions.

**Comment by guillermoturiel** [comment]
Hi, 

Thanks for your fast reply. 

Yes, that's how I generated the GRN file and it looks quite good. However, it is the drug part that doesnt work and at the end it is the most interesting thing for me so it could be great if we can find a way to make it work :)

**Comment by oubounyt** [comment]
Actually, I could not regenerate the error. Can you check the drugstone package version? I have Version: 0.3.5

**Comment by guillermoturiel** [comment]
Indeed that was the solution. I had version 0.3.3 of drugstone and for whatever reason it was not working. I updated the package to version 0.3.6 and worked perfectly. 

Thank you very much!
