### ISSUE TITLE
Request for Assistance: ImportError with 'joblib' in Scikit-learn

### ISSUE THREAD

**Issue by Leslie456456** [oubounyt/SCANet#4]
Hello,

A very nice job! I'm truly impressed with this exceptional tool for single cell analysis.

However, I've encountered an error while working on my project. Below is the traceback for your reference:
Traceback (most recent call last):
ImportError: cannot import name 'joblib' from 'sklearn.externals'

It seems to be an ImportError, likely involving the 'joblib' module within the scikit-learn package, or possibly a version issue with the UMAP package. Could you offer some guidance on resolving this matter?

Thank you very much!

**Comment by Leslie456456** [comment]
And the code with error is: adata = sn.vz.dimensionality_reduction(adata, method="UMAP", n_pcs=10, n_neighbors=10).

**Comment by oubounyt** [comment]
Hey I checked and I have joblib version 1.3.2. Please try to install it using pip install joblib.
