### ISSUE TITLE
databases for GRN inference

### ISSUE THREAD

**Issue by davidrm-bio** [oubounyt/SCANet#5]
Hi, 
Thank you for this cool tool. I manage to follow the tutorial until the inference of the GRN. 

Before running the function for this, we download data using `sn.download_db()`. However, I get HTTP Error 404. I tried checking manually the URL from the script but I get that the website is no longer available. I am not quite sure which files and versions this link included. Could you provide a new link or information on which files I need ?

**Comment by Leslie456456** [comment]
I also encountered the same issue!

**Comment by oubounyt** [comment]
I've identified the issue and am working on resolving it. In the meantime, here are the new links to download the human and mouse datasets:

Human Dataset: https://cloud.uni-hamburg.de/s/YCJkWqebaP5poLH
Mouse Dataset: https://cloud.uni-hamburg.de/s/8ndzG5fm77e6dPG

I will also include these updated links in the upcoming version. If you encounter any further issues or have additional questions, please don't hesitate to reach out.
